// =============================================
// SUPABASE CONFIG
// =============================================
const SUPABASE_URL = 'https://dytnhiwxjmmfcolfnyo.supabase.co';
const SUPABASE_ANON_KEY = 'PASTE_YOUR_ANON_KEY_HERE'; // anon public key jo abhi copy kiya

// Supabase lightweight client (no npm needed, browser fetch)
const supabase = {
  async from(table) {
    return {
      _table: table,
      _filters: [],
      eq(col, val) { this._filters.push({ col, val }); return this; },
      async select(cols = '*') {
        let url = `${SUPABASE_URL}/rest/v1/${this._table}?select=${cols}`;
        this._filters.forEach(f => { url += `&${f.col}=eq.${f.val}`; });
        const res = await fetch(url, {
          headers: {
            'apikey': SUPABASE_ANON_KEY,
            'Authorization': `Bearer ${SUPABASE_ANON_KEY}`
          }
        });
        const data = await res.json();
        return { data, error: res.ok ? null : data };
      },
      async insert(payload) {
        const res = await fetch(`${SUPABASE_URL}/rest/v1/${this._table}`, {
          method: 'POST',
          headers: {
            'apikey': SUPABASE_ANON_KEY,
            'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
            'Content-Type': 'application/json',
            'Prefer': 'return=minimal'
          },
          body: JSON.stringify(payload)
        });
        return { error: res.ok ? null : await res.json() };
      }
    };
  }
};

// =============================================
// FALLBACK LOCAL DATABASE (jab tak Supabase set nahi hoti)
// =============================================
const LOCAL_GUEST_DB = {
  "guest_001": {
    name: "Ramesh Uncle", relation: "uncle", tone: "formal",
    salutation: "Pranam Ramesh Uncle Ji! 🙏",
    script: "Pranam Ramesh Uncle Ji! Main Vipul bol raha hoon. Ek bahut khaas khabar hai — mere bade bhai Arpit ka 40th birthday hai 23 October ko, aur is baar hum usse Diwali ke saath celebrate kar rahe hain! Yeh double celebration hoga — birthday bhi, Diwali bhi — ek hi khaas raat mein. Aapka aashirwaad aur presence is occasion ko truly special bana dega. Please 23 October zaroor save karein!"
  },
  "auntie_formal": {
    name: "Sunita Auntie", relation: "auntie", tone: "formal",
    salutation: "Pranam Sunita Auntie Ji! ✨",
    script: "Pranam Sunita Auntie Ji! Yeh Vipul hoon. Bhaiya Arpit ka 40th birthday 23 October ko hai, aur kyunki Diwali bhi aa rahi hai, hum dono ko ek saath celebrate kar rahe hain! Grand evening plan ki hai — lights, diyas, music, accha khana aur poori family. Aapke bina yeh celebration adhoori lagegi. Please 23 October zaroor save karein!"
  },
  "friend_close": {
    name: "Vikram", relation: "friend", tone: "friendly",
    salutation: "Arre Vikram yaar! 🎉",
    script: "Arre Vikram bhai! Vipul bol raha hoon! Sun na — Arpit bhai ka 40th birthday aa gaya bhai! 23 October! Aur Diwali bhi saath mein hai! Toh hum log ek double dhamaka kar rahe hain — birthday party aur Diwali celebration ek saath! DJ, lights, drinks, badhiya khana, patakhe — poora scene hoga yaar! Yeh raat legendary hone wali hai. Tu toh pakka aayega na? 23 October — date block kar abhi!"
  },
  "friend_casual": {
    name: "Rahul", relation: "friend", tone: "friendly",
    salutation: "Hey Rahul! 🔥",
    script: "Hey Rahul! Vipul this side! Bhai ek game-changing news hai — Arpit bhai 40 ke ho rahe hain 23 October ko! Aur Diwali bhi saath mein hai toh hum ne socha — ek hi night mein dono celebrate karte hain! Epic vibes, amazing food, lights everywhere aur whole squad together! Don't miss this one. 23 October — mark it now!"
  },
  "colleague": {
    name: "Priya Sharma", relation: "colleague", tone: "formal",
    salutation: "Hello Priya! 🌟",
    script: "Hello Priya! Yeh Vipul Khandelwal bol raha hoon. Mere bhai Arpit ka 40th birthday 23 October ko hai, aur since Diwali bhi around the same time hai, hum ne decide kiya ki dono ko ek grand evening mein celebrate karein! Yeh ek very special night hone wali hai aur hum chahte hain ki aap bhi is celebration ka hissa banen. Please 23 October save karein!"
  }
};


// =============================================
// GUEST LOADER — URL param se ya dropdown se
// =============================================
let currentGuest = null;
let speechSynthUtterance = null;
let walkSceneTimer = null;

async function loadGuest(linkId) {
  // Read all params from URL (generated by Google Sheet)
  const urlParams = new URLSearchParams(window.location.search);
  const urlName       = urlParams.get('name');
  const urlType       = urlParams.get('type') || 'birthday';   // birthday / diwali / general
  const urlTone       = urlParams.get('tone') || 'formal';     // formal / friendly
  const urlRelation   = urlParams.get('rel')  || 'friend';

  // If URL has name param (real WhatsApp link from Google Sheet)
  if (urlName) {
    currentGuest = {
      name:        urlName,
      invite_type: urlType,
      tone:        urlTone,
      relation:    urlRelation,
      salutation:  buildSalutation(urlName, urlRelation, urlTone),
      script:      buildScript(urlName, urlType, urlTone, urlRelation)
    };
    return currentGuest;
  }

  // Try Supabase (if configured)
  try {
    if (SUPABASE_URL !== 'YOUR_SUPABASE_URL') {
      const { data, error } = await (await supabase.from('guests')).eq('link_id', linkId).select('*');
      if (!error && data && data.length > 0) {
        currentGuest = data[0];
        return currentGuest;
      }
    }
  } catch (e) {
    console.warn('Supabase not configured, using local fallback');
  }

  // Local fallback DB
  currentGuest = LOCAL_GUEST_DB[linkId] || LOCAL_GUEST_DB['guest_001'];
  return currentGuest;
}

// Build salutation based on relation & tone
function buildSalutation(name, relation, tone) {
  if (tone === 'friendly') {
    if (relation === 'uncle') return `Pranam ${name} Ji! 🙏`;
    if (relation === 'auntie') return `Pranam ${name} Ji! ✨`;
    if (relation === 'friend') return `Arre ${name} yaar! 🎉`;
    if (relation === 'colleague') return `Hey ${name}! 👋`;
    return `Hi ${name}! 👋`;
  }
  // formal
  if (relation === 'uncle') return `Pranam ${name} Ji 🙏`;
  if (relation === 'auntie') return `Pranam ${name} Ji ✨`;
  if (relation === 'colleague') return `Hello ${name} 🙏`;
  return `Hey ${name}! 🎉`;
}

// Build Hinglish script based on invite type, tone, relation
function buildScript(name, inviteType, tone, relation) {
  const scripts = {

    // ─── BIRTHDAY ───────────────────────────────────────────────
    birthday: {
      formal: {
        uncle:
          `Pranam ${name} Ji! Main Vipul bol raha hoon. Bhaiya Arpit ka 40th birthday aa raha hai — 23 October ko. Yeh ek bahut bada milestone hai hamare family ke liye, aur is celebration mein aapka aashirwaad aur presence hamare liye sabse zyada important hai. Ek grand evening plan ki hai — accha khana, music, aur bahut saari khushiyaan. Aap zaroor padhaarein. Hum aapka bahut intezaar karenge.`,

        auntie:
          `Pranam ${name} Ji! Yeh Vipul hoon. Bhaiya Arpit 23 October ko 40 saal ke ho rahe hain aur hum ek special celebration kar rahe hain. Aapka aana is evening ko aur bhi khaas bana dega. Please zaroor aayein — hum aapka wait karenge!`,

        colleague:
          `Hello ${name}! Yeh Vipul Khandelwal bol raha hoon. Mera bada bhai Arpit 23 October ko apna 40th birthday celebrate kar raha hai. Hum chahenge ki aap bhi is special evening ka hissa banen. Ek great evening plan ki hai. Please save the date!`,

        friend:
          `Yaar ${name}! Vipul here! Bhai Arpit ka 40th birthday hai 23 October ko aur hum ek solid party throw kar rahe hain. DJ, great food, drinks — poora setup hoga. Tu toh aayega hi na? Date block kar abhi!`
      },

      friendly: {
        uncle:
          `Pranam ${name} Ji! Main Vipul hoon! Dekho na, Bhaiya Arpit ka 40th birthday aa gaya — 23 October ko! Itna bada occasion hai yaar, aur aapke bina toh yeh celebration adhoori lagegi. Please zaroor aana, hum sab aapka wait karenge. Bohot maza aayega!`,

        auntie:
          `Pranam ${name} Ji! Yeh Vipul hoon! Bhaiya ka 40th birthday 23 October ko hai aur hum sab bohot excited hain! Aap zaroor aana — aapke bina toh party mein kuch missing lagega. Promise hai bahut maza aayega!`,

        colleague:
          `Hey ${name}! Vipul this side! Bhai Arpit turning 40 on October 23rd — aur hum ek super fun celebration plan kar rahe hain. Tu aayega toh aur bhi maza aayega. Block the date, pakka aana!`,

        friend:
          `Arre ${name} bhai! Vipul bol raha hoon! Sun na, Arpit bhai ka 40th birthday hai 23 October ko aur hum log ek full-on party throw kar rahe hain — DJ, dance, drinks, bढia khana, sab kuch! Ek baar toh aana padega yaar. Date block kar abhi!`
      }
    },

    // ─── DIWALI ─────────────────────────────────────────────────
    diwali: {
      formal: {
        uncle:
          `Pranam ${name} Ji! Main Vipul Khandelwal bol raha hoon. Khandelwal family ki taraf se aapko aur aapke poore parivar ko Shubh Deepawali! Is baar hum ghar pe ek special Diwali celebration kar rahe hain aur hum chahte hain ki aap bhi is khushi mein shamil hon. Aapka aashirwaad hamare liye bahut mayne rakhta hai. Zaroor padhaarein!`,

        auntie:
          `Pranam ${name} Ji! Yeh Vipul hoon — Shubh Deepawali! Is baar ghar pe Diwali ka ek khaas celebration hai aur aapka aana is tyohaar ko aur bhi roshan kar dega. Please zaroor aayein!`,

        colleague:
          `Hello ${name}! Vipul this side — Shubh Deepawali to you and your family! Hum is baar ghar pe ek Diwali gathering kar rahe hain aur aapko personally invite karna chahta tha. Hope to see you there!`,

        friend:
          `Happy Diwali ${name}! Vipul here! Is baar Diwali celebration hamare ghar pe — lights, sweets, fireworks, poora scene! Tu toh aa raha hai na? Bohot maza hoga!`
      },

      friendly: {
        uncle:
          `Pranam ${name} Ji! Vipul bol raha hoon — Shubh Deepawali! Is baar ghar pe ek dhamakedar Diwali party plan ki hai. Aap toh aoge na? Aapke bina Diwali adhoori lagegi. Hum sab aapka intezaar karenge!`,

        auntie:
          `Pranam ${name} Ji! Happy Diwali! Yeh Vipul hoon. Hamare ghar Diwali ka bahut bada celebration hai is baar aur aapka aana hamare liye bahut special hoga. Zaroor aana!`,

        colleague:
          `Hey ${name}! Happy Diwali! Vipul here — ghar pe Diwali bash hai, full masti mode on! Tu bhi aa ja, bohot maza aayega. Date pakad le!`,

        friend:
          `Yaar ${name}! Happy Diwali! Vipul here — Diwali dhamaka at our place! Lights, patakhe, sweets, sab kuch hoga. Come na bhai, ek baar toh aana hi padega!`
      }
    },

    // ─── GENERAL ────────────────────────────────────────────────
    general: {
      formal: {
        uncle:    `Pranam ${name} Ji! Main Vipul Khandelwal bol raha hoon. Aapko ek special invitation hai hamare taraf se. Neeche tap karke poori details dekhein. Aapka aana hamare liye bahut khaas hoga!`,
        auntie:   `Pranam ${name} Ji! Yeh Vipul hoon. Ek special occasion hai aur aapko personally invite karna chahta tha. Details neeche hain — zaroor dekhein!`,
        colleague:`Hello ${name}! Vipul this side. Got a special invite for you — please check the details below. Hope to see you there!`,
        friend:   `Arre ${name}! Vipul here — ek khaas invite hai tere liye! Details neeche hain, zaroor dekh!`
      },
      friendly: {
        uncle:    `Pranam ${name} Ji! Vipul bol raha hoon — ek special occasion ke liye aapko invite karna tha. Neeche poori details hain. Zaroor aana!`,
        auntie:   `Pranam ${name} Ji! Yeh Vipul hoon — ek khaas event ke liye aapko bula raha hoon. Details neeche hain!`,
        colleague:`Hey ${name}! Vipul here — check out this special invite made just for you!`,
        friend:   `Yaar ${name}! Vipul here — tera invite ready hai! Dekh neeche, kuch mast plan hai!`
      }
    }
  };

  const typeObj = scripts[inviteType] || scripts.birthday;
  const toneObj = typeObj[tone] || typeObj.formal;
  return toneObj[relation] || toneObj.friend ||
    `Namaste ${name} Ji! Main Vipul Khandelwal bol raha hoon. Aapke liye ek special invite hai — please neeche tap karein!`;
}


// Build script based on invite type, tone, relation
function buildScript(name, inviteType, tone, relation) {
  const scripts = {
    birthday: {
      formal: {
        uncle:    `Respected ${name}, warm greetings. This is Vipul. My elder brother Arpit is celebrating his 40th birthday on the 23rd of October and we would be truly honoured by your blessings and presence. Please save the date.`,
        auntie:   `Respected ${name}, warmest greetings. This is Vipul. We are celebrating Arpit's 40th birthday on October 23rd and your gracious presence would make the evening truly special.`,
        colleague:`Hello ${name}, this is Vipul Khandelwal. I am personally inviting you to my brother Arpit's 40th birthday celebration on October 23rd. It will be a grand evening.`,
        friend:   `Hey ${name}! Vipul here. My brother Arpit turns 40 on October 23rd and we are throwing an incredible party. You have to be there!`
      },
      friendly: {
        uncle:    `Pranam ${name} Ji! Yeh Vipul bol raha hoon. Bhaiya Arpit ka 40th birthday 23 October ko hai. Aapka aana hamare liye sabse important hai. Zaroor padhaarein!`,
        auntie:   `Pranam ${name} Ji! Yeh Vipul hoon. Bhaiya Arpit ka grand 40th birthday celebration hai 23 October ko. Aap zaroor aayein!`,
        colleague:`Hi ${name}! Vipul here. Arpit is turning 40 on October 23rd and we are having a big celebration. Would love to have you there!`,
        friend:   `Arre ${name} yaar! Vipul here! Arpit bhai ka 40th bash hai October 23rd ko! Full party mode — DJ, drinks, great food. Block the date bhai!`
      }
    },
    diwali: {
      formal: {
        uncle:    `Respected ${name}, warm Diwali greetings from the Khandelwal family. This is Vipul. We would be deeply honoured to have you celebrate this auspicious festival with us.`,
        auntie:   `Respected ${name}, Shubh Deepawali! This is Vipul. We warmly invite you to our Diwali celebration.`,
        colleague:`Hello ${name}, Diwali greetings! This is Vipul Khandelwal. On behalf of our family, I would like to warmly invite you to our Diwali celebration.`,
        friend:   `Happy Diwali ${name}! Vipul here! Come join the Khandelwal Diwali party — lights, sweets, fireworks and great fun!`
      },
      friendly: {
        uncle:    `Pranam ${name} Ji! Shubh Deepawali! Yeh Vipul hoon. Hamare ghar Diwali ka bada celebration hai aur aapka aashirwaad hamare liye sabse zaroori hai!`,
        auntie:   `Pranam ${name} Ji! Happy Diwali! Yeh Vipul hoon. Aap zaroor aayein hamare ghar ki Diwali mein!`,
        colleague:`Hey ${name}! Happy Diwali! Vipul here — Diwali party at our place! Hope to see you there!`,
        friend:   `Yaar ${name}! Happy Diwali! Vipul here — Diwali dhamaka at our place! Lights, masti, sweets. Come na!`
      }
    }
  };

  const typeObj = scripts[inviteType] || scripts.birthday;
  const toneObj = typeObj[tone] || typeObj.formal;
  return toneObj[relation] || toneObj.friend || `Hello ${name}, Vipul here with a special invitation for you!`;
}

async function saveRSVP(linkId, response) {
  try {
    if (SUPABASE_URL !== 'YOUR_SUPABASE_URL') {
      const { error } = await (await supabase.from('rsvp_responses')).insert({
        link_id: linkId,
        response: response
      });
      if (!error) console.log('✅ RSVP saved to Supabase!');
    }
  } catch (e) {
    console.warn('RSVP save failed, Supabase not configured');
  }
}

// =============================================
// APP INIT
// =============================================
// =============================================
// MOBILE SPEECH UNLOCK
// iOS & Android block speech without user gesture
// =============================================
function unlockSpeechOnMobile() {
  if ('speechSynthesis' in window) {
    // iOS fix: must call speak() with empty utterance first on user gesture
    const unlock = new SpeechSynthesisUtterance('');
    unlock.volume = 0;
    window.speechSynthesis.speak(unlock);
    window.speechSynthesis.cancel();
  }
}

document.addEventListener("DOMContentLoaded", async () => {
  const urlParams  = new URLSearchParams(window.location.search);
  const urlGuestId = urlParams.get('id');
  const guestSelect = document.getElementById("guest-select");
  const initialId  = urlGuestId || (guestSelect && guestSelect.value) || 'uncle_formal';

  // Hide simulator header when real guest link is used
  if (urlGuestId) {
    const header = document.querySelector('.sim-header');
    if (header) header.style.display = 'none';
  }

  await loadGuest(initialId);
  updateGuestUI();

  if (guestSelect) {
    guestSelect.addEventListener("change", async (e) => {
      stopSpeech();
      await loadGuest(e.target.value);
      updateGuestUI();
    });
  }

  // ─────────────────────────────────────────
  // AUTO-PLAY: Skip intro → go to video immediately
  // ─────────────────────────────────────────
  const hasRealLink = !!urlGuestId;

  if (hasRealLink) {
    // Real guest link → skip intro, straight to video
    setTimeout(() => {
      switchScreen("screen-video");
      setTimeout(() => playVipulMovieScene(), 400);
    }, 600);
  } else {
    // Demo mode → show intro, auto-advance after 2s
    setTimeout(() => {
      switchScreen("screen-video");
      setTimeout(() => playVipulMovieScene(), 400);
    }, 2000);
  }

  // Buttons
  const btnStart = document.getElementById("btn-start-teaser");
  if (btnStart) {
    btnStart.addEventListener("click", () => {
      unlockSpeechOnMobile();
      switchScreen("screen-video");
      setTimeout(() => playVipulMovieScene(), 300);
    });
  }

  const btnSkipCard = document.getElementById("btn-skip-to-card");
  if (btnSkipCard) {
    btnSkipCard.addEventListener("click", () => {
      switchScreen("screen-card");
    });
  }

  document.getElementById("btn-skip-video").addEventListener("click", () => {
    stopSpeech();
    switchScreen("screen-card");
  });

  document.getElementById("btn-rsvp-yes").addEventListener("click", async () => {
    const btn = document.getElementById("btn-rsvp-yes");
    btn.innerHTML = "✨ RSVP Confirmed! See you Oct 23! 🎉";
    btn.style.background = "linear-gradient(135deg, #00b09b, #96c93d)";
    btn.style.color = "#fff";
    await saveRSVP(currentGuest?.link_id || (guestSelect && guestSelect.value), 'attending');
  });

  document.getElementById("btn-add-calendar").addEventListener("click", () => {
    const isIphone = /iPhone|iPad|iPod/i.test(navigator.userAgent);
    const isMac    = /Macintosh/i.test(navigator.userAgent);
    if (isIphone || isMac) {
      window.open('/arpit-40th-diwali.ics', '_blank');
    } else {
      const calUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=Arpit+Khandelwal+40th+Birthday+%26+Diwali+%F0%9F%8E%82%F0%9F%AA%94&dates=20261023T190000/20261023T230000&details=Arpit+Khandelwal+ka+40th+Birthday+aur+Diwali+ka+grand+double+celebration!+Invited+by+Vipul+Khandelwal.&location=Jaipur+(Venue+details+coming+soon)`;
      window.open(calUrl, '_blank');
    }
  });

  // Mobile speech unlock on any touch
  document.addEventListener('touchstart', unlockSpeechOnMobile, { once: true });
});

// =============================================
// VIDEO PLAYBACK — Auto with audio fallback
// =============================================
function playVipulMovieScene() {
  if (!currentGuest) return;
  stopSpeech();

  const mp4Video    = document.getElementById("vipul-mp4-video");
  const walkFrame   = document.getElementById("vipul-walking-frame");
  const locTag      = document.getElementById("party-loc-tag");

  // Show Vipul image while video loads
  walkFrame.src   = "vipul_diwali_walk.jpg";
  walkFrame.style.display = "block";
  mp4Video.style.display  = "none";
  if (locTag) locTag.style.display = "none";

  // ── Try HeyGen MP4 first ──
  mp4Video.src = "https://dytmhiwwjmnfcorlnyci.supabase.co/storage/v1/object/public/VEDIO/vipul_invite.mp4";
  mp4Video.muted = false;

  // Add unmute button for mobile (browsers block audio autoplay)
  addUnmuteButton(mp4Video);

  mp4Video.play()
    .then(() => {
      // ✅ MP4 playing with audio!
      mp4Video.style.display = "block";
      walkFrame.style.display = "none";
      removeUnmuteButton();

      // When video ends → show invite card
      mp4Video.onended = () => {
        setTimeout(() => switchScreen("screen-card"), 800);
      };
    })
    .catch(() => {
      // ❌ MP4 failed → use Vipul image + Speech fallback
      console.log("📽️ MP4 unavailable — using image + voice fallback");
      mp4Video.style.display = "none";
      walkFrame.style.display = "block";
      walkFrame.src = "vipul_diwali_walk.jpg";
      removeUnmuteButton();

      speakScript(currentGuest.script);
    });
}

// ── Unmute button (mobile audio fix) ──
function addUnmuteButton(video) {
  removeUnmuteButton();
  const btn = document.createElement("button");
  btn.id = "unmute-btn";
  btn.innerHTML = "🔊 Tap to Unmute";
  btn.style.cssText = `
    position:absolute; bottom:70px; left:50%;
    transform:translateX(-50%);
    background:rgba(0,0,0,0.7);
    border:1px solid rgba(245,208,97,0.5);
    color:#f5d061; border-radius:50px;
    padding:10px 22px; font-size:0.85rem;
    font-weight:700; cursor:pointer; z-index:100;
    backdrop-filter:blur(10px);
  `;
  btn.onclick = () => {
    video.muted = false;
    video.play();
    removeUnmuteButton();
  };
  const container = document.getElementById("video-container");
  if (container) container.appendChild(btn);
}

function removeUnmuteButton() {
  const btn = document.getElementById("unmute-btn");
  if (btn) btn.remove();
}

// ── Speech Synthesis (fallback voice) ──
function speakScript(script) {
  if (!script || !('speechSynthesis' in window)) {
    // No speech available → auto advance after 8 seconds
    setTimeout(() => switchScreen("screen-card"), 8000);
    return;
  }

  window.speechSynthesis.cancel();
  speechSynthUtterance = new SpeechSynthesisUtterance(script);
  speechSynthUtterance.rate   = 0.88;
  speechSynthUtterance.pitch  = 0.85;
  speechSynthUtterance.volume = 1.0;
  speechSynthUtterance.lang   = 'en-IN';

  const setMaleVoice = () => {
    const voices = window.speechSynthesis.getVoices();
    const prefs  = [
      'Google UK English Male', 'Microsoft David', 'Microsoft Mark',
      'Rishi', 'Daniel', 'Aaron', 'Alex', 'Fred',
      'Google US English', 'en-IN-Wavenet-C'
    ];
    let chosen = null;
    for (const p of prefs) {
      chosen = voices.find(v => v.name.includes(p));
      if (chosen) break;
    }
    if (!chosen) chosen = voices.find(v => v.lang.startsWith('en') && !v.name.toLowerCase().includes('female'));
    if (chosen) {
      speechSynthUtterance.voice = chosen;
      console.log('🎙️ Voice:', chosen.name);
    }
  };

  if (window.speechSynthesis.getVoices().length > 0) setMaleVoice();
  else window.speechSynthesis.onvoiceschanged = setMaleVoice;

  speechSynthUtterance.onend = () => {
    clearTimeout(walkSceneTimer);
    setTimeout(() => switchScreen("screen-card"), 1000);
  };

  // If speech doesn't start in 10s → advance anyway
  walkSceneTimer = setTimeout(() => switchScreen("screen-card"), 15000);

  window.speechSynthesis.speak(speechSynthUtterance);
}

function stopSpeech() {
  clearTimeout(walkSceneTimer);
  if ('speechSynthesis' in window) window.speechSynthesis.cancel();
}


  if (urlGuestId) {
    const header = document.querySelector('.sim-header');
    if (header) header.style.display = 'none';
  }

  await loadGuest(initialId);
  updateGuestUI();

  guestSelect.addEventListener("change", async (e) => {
    await loadGuest(e.target.value);
    updateGuestUI();
  });

  // Unlock speech on first ANY touch/click (mobile requirement)
  document.addEventListener('touchstart', unlockSpeechOnMobile, { once: true });
  document.addEventListener('click', unlockSpeechOnMobile, { once: true });

  document.getElementById("btn-start-teaser").addEventListener("click", () => {
    unlockSpeechOnMobile(); // ensure speech unlocked on this exact gesture
    switchScreen("screen-video");
    // Small delay lets screen transition complete before speech starts
    setTimeout(() => playVipulMovieScene(), 300);
  });

  document.getElementById("btn-skip-video").addEventListener("click", () => {
    stopSpeech();
    switchScreen("screen-card");
  });

  document.getElementById("btn-rsvp-yes").addEventListener("click", async () => {
    const btn = document.getElementById("btn-rsvp-yes");
    btn.innerHTML = "✨ RSVP Confirmed! See you Oct 23! 🎉";
    btn.style.background = "linear-gradient(135deg, #00b09b, #96c93d)";
    btn.style.color = "#fff";
    await saveRSVP(currentGuest?.link_id || guestSelect.value, 'attending');
  });

  document.getElementById("btn-add-calendar").addEventListener("click", () => {
    const isIphone = /iPhone|iPad|iPod/i.test(navigator.userAgent);
    const isMac    = /Macintosh/i.test(navigator.userAgent);

    if (isIphone || isMac) {
      // iPhone / iPad / Mac → ICS file (native Calendar app opens!)
      window.open('/arpit-40th-diwali.ics', '_blank');
    } else {
      // Android / Windows / Others → Google Calendar
      const calUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=Arpit+Khandelwal+40th+Birthday+%26+Diwali+%F0%9F%8E%82%F0%9F%AA%94&dates=20261023T190000/20261023T230000&details=Arpit+Khandelwal+ka+40th+Birthday+aur+Diwali+ka+grand+double+celebration!+Invited+by+Vipul+Khandelwal.&location=Jaipur+(Venue+details+coming+soon)`;
      window.open(calUrl, '_blank');
    }
  });
});

// =============================================
// UI UPDATER
// =============================================
function updateGuestUI() {
  if (!currentGuest) return;
  const el = (id) => document.getElementById(id);
  if (el("intro-greeting")) el("intro-greeting").innerText = currentGuest.salutation || `Dear ${currentGuest.name}`;
  if (el("card-guest-name")) el("card-guest-name").innerText = `Personalized for ${currentGuest.name}`;
}

function switchScreen(screenId) {
  document.querySelectorAll(".screen-view").forEach(s => s.classList.remove("active"));
  document.getElementById(screenId).classList.add("active");
}

// =============================================
// VIDEO PLAYBACK
// =============================================
function playVipulMovieScene() {
  if (!currentGuest) return;
  stopSpeech();

  const mp4Video = document.getElementById("vipul-mp4-video");
  const walkingFrame = document.getElementById("vipul-walking-frame");
  const partyLocTag = document.getElementById("party-loc-tag");

  mp4Video.src = "https://dytmhiwwjmnfcorlnyci.supabase.co/storage/v1/object/public/VEDIO/vipul_invite.mp4";
  mp4Video.play().then(() => {
    mp4Video.style.display = "block";
    walkingFrame.style.display = "none";
    if (partyLocTag) partyLocTag.style.display = "none";
  }).catch(() => {
    mp4Video.style.display = "none";
    walkingFrame.style.display = "block";
    if (partyLocTag) partyLocTag.style.display = "block";

    walkingFrame.src = "vipul_walk_1.jpg";
    if (partyLocTag) partyLocTag.innerText = "📍 VIP LOUNGE • WALKING TO STAGE";

    clearTimeout(walkSceneTimer);
    walkSceneTimer = setTimeout(() => {
      walkingFrame.style.opacity = "0.4";
      setTimeout(() => {
        walkingFrame.src = "vipul_walk_2.jpg";
        walkingFrame.style.opacity = "1";
        if (partyLocTag) partyLocTag.innerText = "📍 MAIN PARTY STAGE • INVITING GUEST";
      }, 400);
    }, 4500);

    if ('speechSynthesis' in window) {
      speechSynthUtterance = new SpeechSynthesisUtterance(currentGuest.script);
      speechSynthUtterance.rate = 0.92;
      speechSynthUtterance.pitch = 0.85;   // Lower pitch = deeper male voice
      speechSynthUtterance.volume = 1.0;
      speechSynthUtterance.lang = 'en-US';

      // Select best available MALE voice
      const setMaleVoice = () => {
        const voices = window.speechSynthesis.getVoices();

        // Priority list of known male voices across browsers/devices
        const maleVoiceNames = [
          'Google UK English Male',      // Chrome desktop
          'Microsoft David',             // Windows Edge/Chrome
          'Microsoft Mark',              // Windows
          'Daniel',                      // iOS/macOS UK male
          'Alex',                        // macOS US male
          'Aaron',                       // macOS US male
          'Fred',                        // macOS
          'Google US English',           // Sometimes male on Android
          'en-US-Wavenet-D',             // Google WaveNet male
          'en-US-Standard-D',            // Google Standard male
          'en-IN-Wavenet-C',             // Indian English male
          'Rishi',                       // iOS Indian English male
        ];

        let selectedVoice = null;

        // Try exact name match first
        for (const name of maleVoiceNames) {
          selectedVoice = voices.find(v => v.name.includes(name));
          if (selectedVoice) break;
        }

        // Fallback: any voice with 'male' in the name
        if (!selectedVoice) {
          selectedVoice = voices.find(v => v.name.toLowerCase().includes('male'));
        }

        // Fallback: any English male-sounding voice
        if (!selectedVoice) {
          selectedVoice = voices.find(v => v.lang.startsWith('en') && !v.name.toLowerCase().includes('female'));
        }

        if (selectedVoice) {
          speechSynthUtterance.voice = selectedVoice;
          console.log('🎙️ Using voice:', selectedVoice.name);
        }
      };

      // Voices may load async — handle both cases
      if (window.speechSynthesis.getVoices().length > 0) {
        setMaleVoice();
      } else {
        window.speechSynthesis.onvoiceschanged = setMaleVoice;
      }

      speechSynthUtterance.onend = () => {
        clearTimeout(walkSceneTimer);
        setTimeout(() => switchScreen("screen-card"), 1200);
      };

      window.speechSynthesis.speak(speechSynthUtterance);
    }
  });
}

function stopSpeech() {
  clearTimeout(walkSceneTimer);
  if ('speechSynthesis' in window) window.speechSynthesis.cancel();
}
